"""add foreign key to Review

Revision ID: 052a614e0342
Revises: d1e45d11220d
Create Date: 2025-01-17 09:47:57.257569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052a614e0342'
down_revision = 'd1e45d11220d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
